export const GET_CHEF_START = 'GET_CHEF_START';
export const GET_CHEF_SUCCESS = 'GET_CHEF_SUCCESS';
export const GET_CHEF_ERROR = 'GET_CHEF_ERROR';
export const GET_ITEM_CHEF_START = 'GET_ITEM_CHEF_START';
export const GET_ITEM_CHEF_SUCCESS = 'GET_ITEM_CHEF_SUCCESS';
export const GET_ITEM_CHEF_ERROR = 'GET_ITEM_CHEF_ERROR';