export const SUBMIT_FORM = 'SUBMIT_FORM';
export const RESET_FORM = 'RESET_FORM';
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const CLEAR_SUCCESS_MESSAGE= 'CLEAR_SUCCESS_MESSAGE';
