export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const GET_ITEM_PRODUCT_START = 'GET_ITEM_PRODUCT_START';
export const GET_ITEM_PRODUCT_SUCCESS = 'GET_ITEM_PRODUCT_SUCCESS';
export const GET_ITEM_PRODUCT_ERROR = 'GET_ITEM_PRODUCT_ERROR';
export const FILTER_PRODUCTS_BY_CATEGORY = 'FILTER_PRODUCTS_BY_CATEGORY';
export const FILTER_PRODUCTS_BY_PRICE_RANGE = 'FILTER_PRODUCTS_BY_PRICE_RANGE';